var avtalen = [avtal1 = {
   bransch: 1,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Kommun- och region­anställda (undersköterskor, vårdbiträden med flera)</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med SKR, Sveriges Kommuner och Regioner</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Sammanhängande anställningstid 365 dagar.</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> 180 kalenderdagar per födsel. Som längst till barnet är två år.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av lönebortfallet, beräknat per kalenderdag.</p>",
   yrke: ["aktiveringsassistent", "aktiveringspedagog", "aktivitetsledare", "arbetshandledare", "badmästare", "badpersonal", "behandlare", "behandlingsassistent", "boendeassistent", "boendehandledare", "boendestödjare", "brandman", "habiliteringsassistent", "ekonomibiträde", "habiliteringsbiträde", "habiliteringspedagog", "habiliteringspersonal", "obduktionstekniker", "omsorgsassistent", "socialpedagog", "stödassistent", "stödbiträde", "stödpedagog", "stödpersonal", "tvätteribiträde", "tvättmaskinskötare", "ambulanssjukvårdare", "anläggningsarbetare", "barnskötare", "barnsköterska", "biträden", "elevassistent", "fastighetsskötare", "fordonsförare", "fotvårdare", "fritidsledare", "förrådsarbetare", "kock", "kokerska", "laboratoriebiträde", "lokalvårdare", "måltidspersonal", "park- och trädgårdsarbetare", "personlig assistent", "skötare", "städare", "undersköterska", "vaktmästare", "vårdare", "vårdbiträde"]
}, avtal2 = {
   bransch: 1,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Anställda i kommun- och regionägda bolag (undersköterskor, vårdbiträden med flera)</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Sobona (fd Pacta)</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Sammanhängande anställningstid 365 dagar.</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> 180 kalenderdagar per födsel. Som längst till barnet är två år.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av lönebortfallet, beräknat per kalenderdag.</p>",
   yrke: ["aktiveringsassistent", "aktiveringspedagog", "aktivitetsledare", "arbetshandledare", "badmästare", "badpersonal", "behandlare", "behandlingsassistent", "boendeassistent", "boendehandledare", "boendestödjare", "brandman", "habiliteringsassistent", "ekonomibiträde", "habiliteringsbiträde", "habiliteringspedagog", "habiliteringspersonal", "obduktionstekniker", "omsorgsassistent", "socialpedagog", "stödassistent", "stödbiträde", "stödpedagog", "stödpersonal", "tvätteribiträde", "tvättmaskinskötare", "ambulanssjukvårdare", "anläggningsarbetare", "barnskötare", "barnsköterska", "biträden", "elevassistent", "fastighetsskötare", "fordonsförare", "fotvårdare", "fritidsledare", "förrådsarbetare", "kock", "kokerska", "laboratoriebiträde", "lokalvårdare", "måltidspersonal", "park- och trädgårdsarbetare", "personlig assistent", "skötare", "städare", "undersköterska", "vaktmästare", "vårdare", "vårdbiträde"]
}, avtal3 = {
   bransch: 3,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Anställda i Svenska Kyrkan</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Svenska Kyrkan</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställningstid anges ej, även säsongsanställda och visstidsanställda får tillägget.</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> 180 kalenderdagar per födsel. Som längst till barnet är tre år.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av lönebortfallet, beräknat per kalenderdag.</p>",
   yrke: ["assistent/församlingsarbete", "fritidsledare", "ungdomsledare", "barntimmeledare", "barnskötare", "diakoniassistent", "arbetsledare", "kyrkvaktmästare", "kyrkogårdsarbetare", "församlingshemsvärd", "husmor", "städare", "fastighetsskötare", "ekonomibiträde", "kontorsvaktmästare", "kyrkogårdsföreståndare", "lokalvårdare"]
}, avtal4 = {
   bransch: 4,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Anställda i privat vård</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Sobona (fd KFS) Vård och omsorg</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst 365 dagar under den senaste treårs­perioden.</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar och max tre ledighetsperioder med minst 30 dagar i följd, som längst till barnet är två år. </p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av lönebortfallet.</p>",
   yrke: ["undersköterska", "vårdbiträde", "ekonomibiträde", "kock", "kokerska", "ungdomsassistent", "behandlingsassistent", "vaktmästare", "handledare"]
}, avtal5E = {
   bransch: 4,
   avtalsoverskrift: "",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Vårdföretagarna, Vård och behandlingsverksamhet samt omsorgsverksamhet (E)</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd under minst ett år i följd samt att anställningen fortsätter i minst 3 månader efter föräldraledigheten.</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid, som längst till barnet är 18 månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> Enligt formel i avtal som motsvarar cirka 10% av lönebortfallet.</p>",
   yrke: ["undersköterska", "vårdbiträde", "kökspersonal", "boendestödjare", "vårdare", "skötare", "lokalvårdare", "fastighetsskötare", "stödassistent"]
}, avtal5F = {
   bransch: 4,
   avtalsoverskrift: "",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Vårdföretagarna, Bransch äldreomsorg (F)</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Två olika system beroende på när företaget blev medlem i Vårdföretagarna. För båda gäller att man ska ha varit anställd i minst ett år. För dem som jobbar i företag som var medlemmar i Vårdföretagarna före den 1 oktober 2012 gäller kravet på anställning minst tre månader efter föräldraledigheten, om inte avtal om FPT finns. (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid, som längst till barnet är 18 månader. Likvärdigt i båda systemen.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> Enligt formel i avtal som motsvarar cirka 10% av lönebortfallet eller 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor. För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["undersköterska", "vårdbiträde", "kökspersonal", "lokalvårdare", "fastighetsskötare"]
}, avtal6 = {
   bransch: 4,
   avtalsoverskrift: "",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med KFO, Kooperationens förhandlingsorganisation, Hälsa, vård och övrig omsorg</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Två olika system beroende på när den anställda är född. För båda gäller att man ska ha varit anställd  i minst ett år. </p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Födda 1980 och tidigare får kollektivavtalets föräldralön i max 150 dagar, om man varit anställd i minst två år. 60 dagar för den som varit anställd i minst ett år. Övriga går på FPT, max 180 dagar beroende på anställningstid innan barnet är 18 månader. (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> Föräldralön ger 10% av månadslön upp till inkomster på max 10 prisbasbelopp (ca 39 400 kronor år 2020). Den som har FPT får 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor. För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["undersköterska", "vårdbiträde", "behandlingsassistent", "socialpedagog", "logopedassistent", "sjukgymnastassistent", "medlevare", "vård- och omsorgspersonal", "lokalvårdare", "köksbiträde", "vaktmästare"]
}, avtal7 = {
   bransch: 4,
   avtalsoverskrift: "",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Arbetsgivaralliansen, Vård- och omsorg</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst sex månader i följd.</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Högst sex månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> Enligt formel i avtal som motsvarar cirka 10% av lönebortfallet.</p>",
   yrke: ["undersköterska", "vårdbiträde", "behandlingsassistent", "socialpedagog", "vårdare", "medlevare", "fältarbetare", "sjukgymnastassistent", "vård- och omsorgspersonal", "lokalvårdare", "kokerska", "kock", "vaktmästare", "ungdomsledare", "fritidsledare", "butikspersonal"]
}, avtal8 = {
   bransch: 5,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Personliga assistenter, ej kommunanställda</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Vårdföretagarna</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst ett år under den senaste fyraårsperioden, hos en eller flera arbetsgivare med FPT. (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid under en period  innan barnet är 18 månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor.  För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["personlig assistent"]
}, avtal9 = {
   bransch: 5,
   avtalsoverskrift: "",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med KFO, Kooperationens Förhandlingsorganisation</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst ett år under den senaste fyraårs­perioden, hos en eller flera arbetsgivare med FPT. (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid under en period innan barnet är 18 månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor. För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["personlig assistent"]
}, avtal10 = {
   bransch: 5,
   avtalsoverskrift: "",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Sobona (fd KFS)</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst ett år under den senaste fyraårs­perioden, hos en eller flera arbetsgivare med FPT.  (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid under en period innan barnet är 18 månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor.  För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["personlig assistent"]
}, avtal13 = {
   bransch: 8,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Bussförare</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Sveriges Bussföretag</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst ett år under den senaste fyraårs­perioden, hos en eller flera arbetsgivare med FPT. (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid under en period innan barnet är 18 månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor.  För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["bussförare", "spårvagnsförare", "verkstadspersonal", "mekaniker", "motorfordonsmekaniker", "reparatör", "lokalvårdare", "garagepersonal", "buss övriga", "chaufför"]
}, avtal14 = {
   bransch: 8,
   avtalsoverskrift: "",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Sobona (fd KFS)</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst ett år under den senaste treårs­perioden.</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar och max tre ledighetsperioder med minst 30 dagar i följd, som längst till barnet är två år.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av lönebortfallet upp till 39 400 kronor. 80% av den del som överstiger 39 400 kronor.</p>",
   yrke: ["bussförare", "spårvagnsförare", "verkstadspersonal", "mekaniker", "motorfordonsmekaniker", "reparatör", "lokalvårdare", "garagepersonal", "buss övriga", "chaufför"]
}, avtal15 = {
   bransch: 9,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Anställda i jordbruk</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Gröna Arbetsgivare (fd SLA)</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst ett år under den senaste fyraårs­perioden, hos en eller flera arbetsgivare med FPT. (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid under en period innan barnet är 18 månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor.  För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["arbetsledare", "traktorförare", "maskinskötare", "maskinförare", "reparatör", "avbytare", "djurskötare", "lantarbetare"]
}, avtal17 = {
   bransch: 11,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Samhallanställda</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Samhall</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst ett år under den senaste fyraårs­perioden, hos en eller flera arbetsgivare med FPT. (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid under en period innan barnet är 18 månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor.  För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["administratör", "chaufför", "driftsledare", "fastighetsskötare", "fönsterputsare", "instruktör", "internlärare", "kundtjänstmedarbetare", "lagerarbetare", "ledsagare", "lokalvårdare", "montör", "receptionist", "renhållningsarbetare", "omsorgsassistent", "serveringsbiträde", "servicevärd", "städare", "teamledare", "tvätterimedarbetare", "vaktmästare"]
}, avtal18 = {
   bransch: 12,
   avtalsoverskrift: "<p class=\"u- u-spacingTopM u-textMetaDeca caps\">Privatanställda städare</p>",
   avtalsrubrik: "<h3 class=\"u-textMetaDeca\">Avtalet med Almega Tjänsteförbunden, serviceentreprenad</h3>",
   avtalstext1: "<p><span class='u-textStrong'>Krav för att få föräldrapenningtillägg:</span> Anställd minst ett år under den senaste fyraårs­perioden, hos en eller flera arbetsgivare med FPT. (FPT = Föräldrapenningtillägg, läs mer på <a href='https://www.afaforsakring.se/privatperson/forsakring-vid-foraldraledighet-och-graviditet/foraldrapenningtillagg/' target='_blank'>afaforsakring.se</a> och <a href='https://www.fora.se/foretag-utan-kollektivavtal/tjanstepension-och-forsakringar/tjanstepension-och-forsakringar-som-ingar/foraldrapenningtillagg-fpt/' target='_blank'>fora.se</a>).</p><p><span class='u-textStrong'>Hur länge får man tillägget?</span> Max 180 dagar beroende på anställningstid under en period innan barnet är 18 månader.</p><p><span class='u-textStrong'>Hur mycket är tillägget?</span> 10% av den lön som ligger till grund för föräldrapenningen upp till en lön på 37 000 kronor.  För dem med högre inkomster gäller andra regler i de flesta fall. Kolla med ditt lokala fack.</p>",
   yrke: ["städare", "lokalvårdare"]
}]
